package ns.cdm.reisinformatie.message.landelijkbericht._1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-08-16T19:27:39.136+02:00
 * Generated source version: 3.5.3
 *
 */
@WebService(targetNamespace = "urn:ns:cdm:reisinformatie:message:landelijkbericht:1", name = "InfoPlusPILInterface")
@XmlSeeAlso({ns.cdm.reisinformatie.data.vi._1.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface InfoPlusPILInterface {

    @WebMethod(operationName = "PutReisInformatieBoodschap", action = "PutReisInformatieBoodschap")
    @WebResult(name = "PutReisInformatieBoodschapOut", targetNamespace = "urn:ns:cdm:reisinformatie:message:landelijkbericht:1", partName = "PutReisInformatieBoodschapOut")
    public PutReisInformatieBoodschapOut putReisInformatieBoodschap(

        @WebParam(partName = "PutReisInformatieBoodschapIn", name = "PutReisInformatieBoodschapIn", targetNamespace = "urn:ns:cdm:reisinformatie:message:landelijkbericht:1")
        PutReisInformatieBoodschapIn putReisInformatieBoodschapIn
    );
}
